name: Rust - Release creation

on:
  release:
    types: [created]

jobs:
  create-release:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: pyadb_client

    steps:
      - uses: actions/checkout@v4

      - name: Install Python dependencies
        run: pip install .

      - name: Publish Python package
        run: maturin publish --non-interactive
        env:
          MATURIN_PYPI_TOKEN: ${{ secrets.MATURIN_PYPI_TOKEN }}

      - name: "Publish GitHub artefacts"
        uses: softprops/action-gh-release@v2
        with:
          files: |
            target/wheels/pyadb_client*.whl
            target/wheels/pyadb_client*.tar.gz
